FROM node:20-alpine
WORKDIR /app

COPY package.json ./
COPY server/package.json ./server/
COPY client/package.json ./client/

RUN cd server && npm install
RUN cd client && npm install
RUN npm install

COPY server/ ./server/
COPY client/ ./client/

RUN cd server && npx prisma generate

EXPOSE 3001 5173

CMD ["npm", "run", "dev"]
