import express from "express";
import cors from "cors";
import helmet from "helmet";
import { config } from "./config";
import { logger } from "./middleware/logger";
import { errorHandler } from "./middleware/errorHandler";
import { apiLimiter, loginLimiter, mrpLimiter, datasetLimiter, exportLimiter, registerLimiter } from "./middleware/rateLimiter";
import authRoutes from "./routes/auth";
import financeRoutes from "./routes/finance";
import materialsRoutes from "./routes/materials";
import salesRoutes from "./routes/sales";
import productionRoutes from "./routes/production";
import warehouseRoutes from "./routes/warehouse";
import qualityRoutes from "./routes/quality";
import maintenanceRoutes from "./routes/maintenance";
import hrRoutes from "./routes/hr";
import controllingRoutes from "./routes/controlling";
import reportingRoutes from "./routes/reporting";
import workflowRoutes from "./routes/workflow";
import adminRoutes from "./routes/admin";
import learningRoutes from "./routes/learning";
import mrpRoutes from "./routes/mrp";
import schedulingRoutes from "./routes/scheduling";
import supplyChainRoutes from "./routes/supply-chain";
import processMiningRoutes from "./routes/process-mining";
import inventoryPoliciesRoutes from "./routes/inventory-policies";
import gamificationRoutes from "./routes/gamification";
import operationsRoutes from "./routes/operations";
import utilitiesRoutes from "./routes/utilities";
import apRoutes from "./routes/ap";
import arRoutes from "./routes/ar";
import enhancedInventoryRoutes from "./routes/enhanced-inventory";
import pricingRoutes from "./routes/pricing";
import timeMachineRoutes from "./routes/time-machine";
import simulatorRoutes from "./routes/simulator";
import explainerRoutes from "./routes/explainer";
import instructorRoutes from "./routes/instructor";
import assetsRoutes from "./routes/assets";
import transportRoutes from "./routes/transport";
import costingRoutes from "./routes/costing";
import multiCompanyRoutes from "./routes/multi-company";
import financialStatementsRoutes from "./routes/financial-statements";
import periodClosingRoutes from "./routes/period-closing";
import mrpBoardRoutes from "./routes/mrp-board";
import portalsRoutes from "./routes/portals";
import dataWarehouseRoutes from "./routes/data-warehouse";
import optimizationRoutes from "./routes/optimization";
import integrationRoutes from "./routes/integration";
import documentsRoutes from "./routes/documents";
import coursesRoutes from "./routes/courses";
import certificationRoutes from "./routes/certification";
import datasetGeneratorRoutes from "./routes/dataset-generator";
import monitoringRoutes from "./routes/monitoring";
import processFlowsRoutes from "./routes/process-flows";
import digitalTwinRoutes from "./routes/digital-twin";
import industryTemplatesRoutes from "./routes/industry-templates";
import decisionImpactRoutes from "./routes/decision-impact";
import benchmarkRoutes from "./routes/benchmark";
import stressTestRoutes from "./routes/stress-test";
import sqlExplorerRoutes from "./routes/sql-explorer";
import collaborationRoutes from "./routes/collaboration";
import auditAdvancedRoutes from "./routes/audit-advanced";
import notificationsRoutes from "./routes/notifications";
import profileRoutes from "./routes/profile";
import studentSandboxRoutes from "./routes/student-sandbox";
import gameModeRoutes from "./routes/game-mode";
import instructorAnalyticsRoutes from "./routes/instructor-analytics";
import searchRoutes from "./routes/search";
import jobsRoutes from "./routes/jobs";
import learningAnalyticsRoutes from "./routes/learning-analytics";
import assignmentsRoutes from "./routes/assignments";
import dataExportRoutes from "./routes/data-export";
import ssoRoutes from "./routes/sso";
import eventBusRoutes from "./routes/event-bus";
import copilotRoutes from "./routes/copilot";
import simulationRoutes from "./routes/simulation";
import experimentLabRoutes from "./routes/experiment-lab";
import scenarioReplayRoutes from "./routes/scenario-replay";
import recommendationsRoutes from "./routes/recommendations";
import forecastingRoutes from "./routes/forecasting";
import multiEchelonRoutes from "./routes/multi-echelon";

const app = express();

app.use(helmet());
app.use(cors({ origin: config.corsOrigin, credentials: true }));
app.use(express.json({ limit: "10mb" }));
app.use(apiLimiter);

app.use("/api/auth/login", loginLimiter);
app.use("/api/auth/register", registerLimiter);
app.use("/api/auth", authRoutes);
app.use("/api/sso", ssoRoutes);
app.use("/api/finance", financeRoutes);
app.use("/api/materials", materialsRoutes);
app.use("/api/sales", salesRoutes);
app.use("/api/production", productionRoutes);
app.use("/api/warehouse", warehouseRoutes);
app.use("/api/quality", qualityRoutes);
app.use("/api/maintenance", maintenanceRoutes);
app.use("/api/hr", hrRoutes);
app.use("/api/controlling", controllingRoutes);
app.use("/api/reporting", reportingRoutes);
app.use("/api/workflow", workflowRoutes);
app.use("/api/admin", adminRoutes);
app.use("/api/learning", learningRoutes);
app.use("/api/mrp", mrpLimiter, mrpRoutes);
app.use("/api/scheduling", schedulingRoutes);
app.use("/api/supply-chain", supplyChainRoutes);
app.use("/api/process-mining", processMiningRoutes);
app.use("/api/inventory-policies", inventoryPoliciesRoutes);
app.use("/api/gamification", gamificationRoutes);
app.use("/api/operations", operationsRoutes);
app.use("/api/utilities", utilitiesRoutes);
app.use("/api/ap", apRoutes);
app.use("/api/ar", arRoutes);
app.use("/api/enhanced-inventory", enhancedInventoryRoutes);
app.use("/api/pricing", pricingRoutes);
app.use("/api/time-machine", timeMachineRoutes);
app.use("/api/simulator", simulatorRoutes);
app.use("/api/explainer", explainerRoutes);
app.use("/api/instructor", instructorRoutes);
app.use("/api/assets", assetsRoutes);
app.use("/api/transport", transportRoutes);
app.use("/api/costing", costingRoutes);
app.use("/api/multi-company", multiCompanyRoutes);
app.use("/api/financial-statements", financialStatementsRoutes);
app.use("/api/period-closing", periodClosingRoutes);
app.use("/api/mrp-board", mrpBoardRoutes);
app.use("/api/portals", portalsRoutes);
app.use("/api/data-warehouse", dataWarehouseRoutes);
app.use("/api/optimization", optimizationRoutes);
app.use("/api/integration", integrationRoutes);
app.use("/api/documents", documentsRoutes);
app.use("/api/courses", coursesRoutes);
app.use("/api/certification", certificationRoutes);
app.use("/api/dataset-generator", datasetLimiter, datasetGeneratorRoutes);
app.use("/api/monitoring", monitoringRoutes);
app.use("/api/process-flows", processFlowsRoutes);
app.use("/api/digital-twin", digitalTwinRoutes);
app.use("/api/industry-templates", industryTemplatesRoutes);
app.use("/api/decision-impact", decisionImpactRoutes);
app.use("/api/benchmark", benchmarkRoutes);
app.use("/api/stress-test", stressTestRoutes);
app.use("/api/sql-explorer", sqlExplorerRoutes);
app.use("/api/collaboration", collaborationRoutes);
app.use("/api/audit-advanced", auditAdvancedRoutes);
app.use("/api/notifications", notificationsRoutes);
app.use("/api/profile", profileRoutes);
app.use("/api/student-sandbox", studentSandboxRoutes);
app.use("/api/game-mode", gameModeRoutes);
app.use("/api/instructor-analytics", instructorAnalyticsRoutes);
app.use("/api/search", searchRoutes);
app.use("/api/jobs", jobsRoutes);
app.use("/api/learning-analytics", learningAnalyticsRoutes);
app.use("/api/assignments", assignmentsRoutes);
app.use("/api/data-export", exportLimiter, dataExportRoutes);
app.use("/api/event-bus", eventBusRoutes);
app.use("/api/copilot", copilotRoutes);
app.use("/api/simulation", simulationRoutes);
app.use("/api/experiment-lab", experimentLabRoutes);
app.use("/api/scenario-replay", scenarioReplayRoutes);
app.use("/api/recommendations", recommendationsRoutes);
app.use("/api/forecasting", forecastingRoutes);
app.use("/api/multi-echelon", multiEchelonRoutes);

app.get("/api/health", (_req, res) => {
  res.json({ status: "ok", timestamp: new Date().toISOString() });
});

app.use(errorHandler);

app.listen(config.port, () => {
  logger.info(`Server running on http://localhost:${config.port}`);
});

export default app;
